languages: minimal

services:
  - docker
before_install:
  - uname -a
  - perl --version
  - prove --version
  - cpanm --version

install:
  - docker pull jjmerelo/raku-test

script:
  - docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
